// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY2IgPAdppVKW8p3SXnQMxrv9zkvaC55o',
    appId: '1:711951795992:web:110cb6db0b13d45141806d',
    messagingSenderId: '711951795992',
    projectId: 'food-delivery-26ab5',
    authDomain: 'food-delivery-26ab5.firebaseapp.com',
    storageBucket: 'food-delivery-26ab5.appspot.com',
    measurementId: 'G-G7XTM48JMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqjROgqGfVx3-40J7ht63LaVevQiOPhN8',
    appId: '1:711951795992:android:10585219b1f915c141806d',
    messagingSenderId: '711951795992',
    projectId: 'food-delivery-26ab5',
    storageBucket: 'food-delivery-26ab5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA34MyFL5mlGb_Vkmy57NJZNPn3XzmOEVI',
    appId: '1:711951795992:ios:0c6eef3af123c00741806d',
    messagingSenderId: '711951795992',
    projectId: 'food-delivery-26ab5',
    storageBucket: 'food-delivery-26ab5.appspot.com',
    iosBundleId: 'com.example.tStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA34MyFL5mlGb_Vkmy57NJZNPn3XzmOEVI',
    appId: '1:711951795992:ios:0c6eef3af123c00741806d',
    messagingSenderId: '711951795992',
    projectId: 'food-delivery-26ab5',
    storageBucket: 'food-delivery-26ab5.appspot.com',
    iosBundleId: 'com.example.tStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY2IgPAdppVKW8p3SXnQMxrv9zkvaC55o',
    appId: '1:711951795992:web:e9695cd2401f400741806d',
    messagingSenderId: '711951795992',
    projectId: 'food-delivery-26ab5',
    authDomain: 'food-delivery-26ab5.firebaseapp.com',
    storageBucket: 'food-delivery-26ab5.appspot.com',
    measurementId: 'G-0R3E6RB0W3',
  );
}
